SET client_min_messages TO WARNING;

-- Inserção de usuários
INSERT INTO usuarios (email, password, is_admin) VALUES
('maria.silva@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('joao.santos@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('ana.oliveira@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('carlos.pereira@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('julia.rodrigues@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('marcos.almeida@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('fernanda.lima@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('ricardo.souza@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('patricia.costa@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', false),
('admin@example.com', '$2a$10$xJwL5v5z5U6JZ5JZ5JZ5ZuJZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5JZ5', true);

-- Inserção de questionários socioeconômicos
INSERT INTO questionarios_socioeconomicos (nome, idade, genero, raca_cor, escolaridade, estado_civil, emprego, dependentes, religiao) VALUES
('Maria da Silva', 35, 'FEMININO', 'PARDO', 'ENSINO_MEDIO_COMPLETO', 'CASADO', 'DESEMPREGADO', 'DOIS', 'CATOLICO'),
('João Santos', 28, 'MASCULINO', 'PRETO', 'GRADUACAO_INCOMPLETA', 'SOLTEIRO', 'MEIO_PERIODO', 'UM', 'EVANGELICO'),
('Ana Oliveira', 42, 'FEMININO', 'BRANCO', 'ENSINO_FUNDAMENTAL_COMPLETO', 'SEPARADO', 'DESEMPREGADO', 'TRES', 'NENHUMA'),
('Carlos Pereira', 50, 'MASCULINO', 'PARDO', 'ENSINO_FUNDAMENTAL_INCOMPLETO', 'VIUVO', 'APOSENTADO', 'NENHUM', 'ESPIRITA'),
('Julia Rodrigues', 22, 'FEMININO', 'BRANCO', 'GRADUACAO_COMPLETA', 'SOLTEIRO', 'MEIO_PERIODO', 'UM', 'CATOLICO'),
('Marcos Almeida', 38, 'MASCULINO', 'PRETO', 'ENSINO_MEDIO_INCOMPLETO', 'CASADO', 'DESEMPREGADO', 'CINCO_OU_MAIS', 'EVANGELICO'),
('Fernanda Lima', 45, 'FEMININO', 'PARDO', 'ENSINO_FUNDAMENTAL_COMPLETO', 'DIVORCIADO', 'INCAPAZ_TRABALHAR', 'DOIS', 'NENHUMA'),
('Ricardo Souza', 31, 'MASCULINO', 'BRANCO', 'GRADUACAO_INCOMPLETA', 'SOLTEIRO', 'MEIO_PERIODO', 'NENHUM', 'CATOLICO'),
('Patricia Costa', 29, 'FEMININO', 'POVOS_ORIGINARIOS', 'ENSINO_MEDIO_COMPLETO', 'CASADO', 'DESEMPREGADO', 'TRES', 'EVANGELICO'),
('Administrador', 40, 'MASCULINO', 'BRANCO', 'GRADUACAO_COMPLETA', 'CASADO', 'MEIO_PERIODO', 'UM', 'NENHUMA');

-- Inserção de auxílios governamentais
INSERT INTO auxilios (questionario_id, auxilios) VALUES
(1, 'BOLSA_FAMILIA'),
(1, 'AUXILIO_EMERGENCIAL'),
(2, 'AUXILIO_BRASIL'),
(3, 'BOLSA_FAMILIA'),
(4, 'BPC'),
(6, 'BOLSA_FAMILIA'),
(6, 'VALE_GAS'),
(7, 'AUXILIO_EMERGENCIAL'),
(9, 'BOLSA_FAMILIA'),
(9, 'AUXILIO_BRASIL');

-- Inserção de marcadores de consumo
INSERT INTO marcadores_consumo (feijao, frutas_frescas, verduras_legumes, hamburguer_embutidos, bebidas_adocadas, industrializados_salgados, doces_guloseimas) VALUES
(true, false, true, false, true, false, true),
(false, true, false, true, false, true, false),
(true, true, true, false, false, true, false),
(false, false, false, true, true, false, true),
(true, true, false, true, false, true, false),
(false, false, true, false, true, false, true),
(true, false, false, true, false, true, false),
(false, true, true, false, false, true, true),
(true, false, true, false, true, false, false),
(false, true, false, true, false, true, true);

-- Inserção de refeições diárias
INSERT INTO refeicoes_diarias (consumo_id, refeicoes_diarias) VALUES
(1, 'CAFE_DA_MANHA'),
(1, 'ALMOCO'),
(1, 'JANTAR'),
(2, 'CAFE_DA_MANHA'),
(2, 'LANCHE_DA_MANHA'),
(2, 'ALMOCO'),
(2, 'LANCHE_DA_TARDE'),
(3, 'ALMOCO'),
(3, 'JANTAR'),
(4, 'CAFE_DA_MANHA'),
(4, 'JANTAR'),
(5, 'CAFE_DA_MANHA'),
(5, 'ALMOCO'),
(5, 'LANCHE_DA_TARDE'),
(5, 'JANTAR'),
(6, 'ALMOCO'),
(7, 'CAFE_DA_MANHA'),
(7, 'ALMOCO'),
(7, 'LANCHE_DA_TARDE'),
(8, 'ALMOCO'),
(8, 'JANTAR'),
(9, 'CAFE_DA_MANHA'),
(9, 'ALMOCO'),
(10, 'ALMOCO'),
(10, 'LANCHE_DA_TARDE'),
(10, 'JANTAR');

-- Inserção de respostas EBIA
INSERT INTO ebia_respostas (respostas) VALUES
('{1: "SIM", 2: "SIM", 3: "NAO", 4: "NAO", 5: "SIM", 6: "NAO", 7: "NAO", 8: "NAO"}'),
('{1: "NAO", 2: "NAO", 3: "NAO", 4: "NAO", 5: "NAO", 6: "NAO", 7: "NAO", 8: "NAO"}'),
('{1: "SIM", 2: "SIM", 3: "SIM", 4: "SIM", 5: "SIM", 6: "SIM", 7: "SIM", 8: "SIM"}'),
('{1: "NAO", 2: "SIM", 3: "NAO", 4: "SIM", 5: "NAO", 6: "SIM", 7: "NAO", 8: "SIM"}'),
('{1: "NAO", 2: "NAO", 3: "SIM", 4: "NAO", 5: "NAO", 6: "NAO", 7: "NAO", 8: "NAO"}'),
('{1: "SIM", 2: "SIM", 3: "SIM", 4: "NAO", 5: "NAO", 6: "NAO", 7: "NAO", 8: "NAO"}'),
('{1: "SIM", 2: "SIM", 3: "SIM", 4: "SIM", 5: "SIM", 6: "NAO", 7: "NAO", 8: "NAO"}'),
('{1: "NAO", 2: "NAO", 3: "NAO", 4: "NAO", 5: "NAO", 6: "NAO", 7: "NAO", 8: "NAO"}'),
('{1: "SIM", 2: "SIM", 3: "NAO", 4: "NAO", 5: "NAO", 6: "NAO", 7: "NAO", 8: "NAO"}'),
('{1: "NAO", 2: "NAO", 3: "NAO", 4: "NAO", 5: "NAO", 6: "NAO", 7: "NAO", 8: "NAO"}');

-- Inserção de perguntas e respostas EBIA
INSERT INTO ebia_perguntas_respostas (ebia_id, pergunta_numero, resposta) VALUES
(1, 1, 'SIM'),
(1, 2, 'SIM'),
(1, 3, 'NAO'),
(1, 4, 'NAO'),
(1, 5, 'SIM'),
(1, 6, 'NAO'),
(1, 7, 'NAO'),
(1, 8, 'NAO'),
(2, 1, 'NAO'),
(2, 2, 'NAO'),
(2, 3, 'NAO'),
(2, 4, 'NAO'),
(2, 5, 'NAO'),
(2, 6, 'NAO'),
(2, 7, 'NAO'),
(2, 8, 'NAO'),
(3, 1, 'SIM'),
(3, 2, 'SIM'),
(3, 3, 'SIM'),
(3, 4, 'SIM'),
(3, 5, 'SIM'),
(3, 6, 'SIM'),
(3, 7, 'SIM'),
(3, 8, 'SIM'),
(4, 1, 'NAO'),
(4, 2, 'SIM'),
(4, 3, 'NAO'),
(4, 4, 'SIM'),
(4, 5, 'NAO'),
(4, 6, 'SIM'),
(4, 7, 'NAO'),
(4, 8, 'SIM'),
(5, 1, 'NAO'),
(5, 2, 'NAO'),
(5, 3, 'SIM'),
(5, 4, 'NAO'),
(5, 5, 'NAO'),
(5, 6, 'NAO'),
(5, 7, 'NAO'),
(5, 8, 'NAO'),
(6, 1, 'SIM'),
(6, 2, 'SIM'),
(6, 3, 'SIM'),
(6, 4, 'NAO'),
(6, 5, 'NAO'),
(6, 6, 'NAO'),
(6, 7, 'NAO'),
(6, 8, 'NAO'),
(7, 1, 'SIM'),
(7, 2, 'SIM'),
(7, 3, 'SIM'),
(7, 4, 'SIM'),
(7, 5, 'SIM'),
(7, 6, 'NAO'),
(7, 7, 'NAO'),
(7, 8, 'NAO'),
(8, 1, 'NAO'),
(8, 2, 'NAO'),
(8, 3, 'NAO'),
(8, 4, 'NAO'),
(8, 5, 'NAO'),
(8, 6, 'NAO'),
(8, 7, 'NAO'),
(8, 8, 'NAO'),
(9, 1, 'SIM'),
(9, 2, 'SIM'),
(9, 3, 'NAO'),
(9, 4, 'NAO'),
(9, 5, 'NAO'),
(9, 6, 'NAO'),
(9, 7, 'NAO'),
(9, 8, 'NAO'),
(10, 1, 'NAO'),
(10, 2, 'NAO'),
(10, 3, 'NAO'),
(10, 4, 'NAO'),
(10, 5, 'NAO'),
(10, 6, 'NAO'),
(10, 7, 'NAO'),
(10, 8, 'NAO');

-- Inserção de avaliações completas
INSERT INTO avaliacoes (data_cadastro, questionario_id, consumo_id, ebia_id, user_id, concluida, classificacao) VALUES
('2024-01-15 10:00:00', 1, 1, 1, 1, true, 'INSEGURANCA_MODERADA'),
('2024-01-16 11:30:00', 2, 2, 2, 2, true, 'SEGURANCA_ALIMENTAR'),
('2024-01-17 09:15:00', 3, 3, 3, 3, true, 'INSEGURANCA_GRAVE'),
('2024-01-18 14:45:00', 4, 4, 4, 4, true, 'INSEGURANCA_MODERADA'),
('2024-01-19 16:20:00', 5, 5, 5, 5, true, 'SEGURANCA_ALIMENTAR'),
('2024-01-20 08:30:00', 6, 6, 6, 6, false, 'INSEGURANCA_MODERADA'),
('2024-01-21 13:10:00', 7, 7, 7, 7, true, 'INSEGURANCA_GRAVE'),
('2024-01-22 15:45:00', 8, 8, 8, 8, true, 'SEGURANCA_ALIMENTAR'),
('2024-01-23 10:30:00', 9, 9, 9, 9, false, 'INSEGURANCA_MODERADA'),
('2024-01-24 12:00:00', 10, 10, 10, 10, true, 'SEGURANCA_ALIMENTAR');